### ISSUE TITLE
Should *Table.row_cls be private (_row_cls)?

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/ae7qparser#13]
this also affects documentation, as currently this is what it looks like:
![image](https://user-images.githubusercontent.com/5366828/81454801-42fab700-915b-11ea-9170-0ead70fd9965.png)

**Comment by classabbyamp** [comment]
I think so

**Comment by 0x5c** [comment]
hum ya

**Comment by classabbyamp** [comment]
great
